### ISSUE TITLE
TeamBeamJS does not work with many files

### ISSUE THREAD

**Issue by desc** [skalio/teambeamjs#21]
I tried to upload several files with teambeamjs but get a 429 error message back, which indicates "Too Many Requests". The dataset contains 135 files with 13.7 GB at all. So it seems that the upload exceeds a connection or request limit.

Here is the output of the upload attempt:

<pre>Logging in user "username@domain.tld"
User "username@domain.tld" has logged in successfully
Creating new reservation
Reservation 9fca79tymud8ld3l5hpvyww78wxfbxe1n4nbgrx8 created
Uploading h3jeqjxzez (3,888,513,024 Bytes)
Uploading h3jeqjy051 (74,724 Bytes)
Uploading h3jeqjy0o6 (150,494 Bytes)
Uploading h3jeqjy17m (30,233,250 Bytes)
Uploading h3jeqjy1pu (118,021 Bytes)
Uploading h3jeqjy2br (4,416,475 Bytes)
Uploading h3jeqjy2yg (102,431 Bytes)
Uploading h3jeqjy3hr (3,671,330 Bytes)
Uploading h3jeqjy402 (143,895 Bytes)
Uploading h3jeqjy4iw (4,873,796 Bytes)
Uploading h3jeqjy513 (163,168 Bytes)
Uploading h3jeqjy5lc (5,253,774 Bytes)
Uploading h3jeqjy64j (116,284 Bytes)
Uploading h3jeqjy6pe (3,455,493 Bytes)
Uploading h3jeqjy7xj (196,033 Bytes)
Uploading h3jeqjy8ha (5,464,292 Bytes)
Uploading h3jeqjy932 (176,355 Bytes)
Uploading h3jeqjy9nu (4,388,693 Bytes)
Uploading h3jeqjya9n (104,435 Bytes)
Uploading h3jeqjyauf (2,523,288 Bytes)
Uploading h3jeqjybe6 (44,604 Bytes)
Uploading h3jeqjybx8 (987,979 Bytes)
Uploading h3jeqjycge (27,622 Bytes)
Uploading h3jeqjyd1e (601,359 Bytes)
Uploading h3jeqjydl2 (66,633 Bytes)
Uploading h3jeqjye56 (3,295,813 Bytes)
Uploading h3jeqjyep6 (79,577 Bytes)
Uploading h3jeqjyf9k (3,744,864 Bytes)
Uploading h3jeqjyg6u (81,614 Bytes)
Uploading h3jeqjyh02 (3,506,052 Bytes)
Uploading h3jeqjyhr5 (42,306 Bytes)
Uploading h3jeqjyifh (1,841,878 Bytes)
Uploading h3jeqjyj2q (87,936 Bytes)
Uploading h3jeqjyjo7 (3,701,357 Bytes)
Uploading h3jeqjyk9j (69,081 Bytes)
Uploading h3jeqjyksu (2,806,515 Bytes)
Uploading h3jeqjylbl (45,454 Bytes)
Uploading h3jeqjylua (1,902,657 Bytes)
Uploading h3jeqjymeu (119,485 Bytes)
Uploading h3jeqjyn35 (4,661,001 Bytes)
Uploading h3jeqjynyo (676,331,520 Bytes)
Uploading h3jeqjyomc (26,371 Bytes)
Uploading h3jeqjyp8a (45,598 Bytes)
Uploading h3jeqjyptz (6,820,354 Bytes)
Uploading h3jeqjyqfs (396,361,728 Bytes)
Uploading h3jeqjyqzx (30,786 Bytes)
Uploading h3jeqjyrl0 (27,895 Bytes)
Uploading h3jeqjysat (4,781,987 Bytes)
Uploading h3jeqjysvm (3,985,485,824 Bytes)
Uploading h3jeqjytni (76,564 Bytes)
Uploading h3jeqjyudi (150,984 Bytes)
Uploading h3jeqjyuyn (28,848,854 Bytes)
Uploading h3jeqjyvnh (144,489 Bytes)
Uploading h3jeqjyw9p (5,323,131 Bytes)
Uploading h3jeqjywv2 (128,299 Bytes)
Uploading h3jeqjyxh2 (4,417,634 Bytes)
Uploading h3jeqjyy2y (155,909 Bytes)
Uploading h3jeqjyyqd (5,068,913 Bytes)
Uploading h3jeqjyzbq (181,332 Bytes)
Uploading h3jeqjyzvr (5,435,561 Bytes)
Uploading h3jeqjz0hu (245,226 Bytes)
Uploading h3jeqjz12r (6,641,995 Bytes)
Uploading h3jeqjz1pl (179,072 Bytes)
Uploading h3jeqjz2ft (4,313,107 Bytes)
Uploading h3jeqjz2zk (38,385 Bytes)
Uploading h3jeqjz3jt (975,101 Bytes)
Uploading h3jeqjz46h (14,053 Bytes)
Uploading h3jeqjz4qx (265,564 Bytes)
Uploading h3jeqjz5b8 (25,546 Bytes)
Uploading h3jeqjz5vj (579,249 Bytes)
Uploading h3jeqjz6i7 (71,021 Bytes)
Uploading h3jeqjz7cl (3,477,156 Bytes)
Uploading h3jeqjz803 (72,207 Bytes)
Uploading h3jeqjz8jv (3,400,713 Bytes)
Uploading h3jeqjz937 (94,110 Bytes)
Uploading h3jeqjz9me (4,093,780 Bytes)
Uploading h3jeqjza8i (45,655 Bytes)
Uploading h3jeqjzb2o (1,939,565 Bytes)
Uploading h3jeqjzbr7 (83,912 Bytes)
Uploading h3jeqjzcmw (3,510,617 Bytes)
Uploading h3jeqjzdd9 (54,929 Bytes)
Uploading h3jeqjze4i (2,202,323 Bytes)
Uploading h3jeqjzexc (73,952 Bytes)
Uploading h3jeqjzfk8 (3,078,520 Bytes)
Uploading h3jeqjzg8i (138,359 Bytes)
Uploading h3jeqjzgyo (5,231,032 Bytes)
Uploading h3jeqjzhks (335,851,520 Bytes)
Uploading h3jeqjzi92 (26,186 Bytes)
Uploading h3jeqjzivf (26,343 Bytes)
Uploading h3jeqjzjif (4,829,636 Bytes)
Uploading h3jeqjzk6a (3,972,317,184 Bytes)
Uploading h3jeqjzksy (76,319 Bytes)
Uploading h3jeqjzlhc (151,076 Bytes)
Uploading h3jeqjzm47 (30,135,570 Bytes)
Uploading h3jeqjzmr5 (153,495 Bytes)
Uploading h3jeqjzneq (5,785,376 Bytes)
Uploading h3jeqjzo1w (123,040 Bytes)
Uploading h3jeqjzooy (4,302,150 Bytes)
Uploading h3jeqjzpfj (128,298 Bytes)
Uploading h3jeqjzq5e (4,254,233 Bytes)
Uploading h3jeqjzqqy (172,415 Bytes)
Uploading h3jeqjzrby (5,392,772 Bytes)
Uploading h3jeqjzrxu (184,256 Bytes)
Uploading h3jeqjzsnt (5,250,194 Bytes)
Uploading h3jeqjztax (234,090 Bytes)
Uploading h3jeqjzty0 (5,998,328 Bytes)
Uploading h3jeqjzujg (100,047 Bytes)
Uploading h3jeqjzv6a (2,422,303 Bytes)
Uploading h3jeqjzvxc (33,638 Bytes)
Uploading h3jeqjzwn7 (854,158 Bytes)
Uploading h3jeqjzxpc (15,849 Bytes)
Uploading h3jeqjzyks (287,819 Bytes)
Uploading h3jeqjzzls (27,068 Bytes)
Uploading h3jeqk00ru (592,206 Bytes)
Uploading h3jeqk01ng (66,411 Bytes)
Uploading h3jeqk02dr (3,290,776 Bytes)
Uploading h3jeqk0348 (79,447 Bytes)
Uploading h3jeqk03te (3,735,742 Bytes)
Uploading h3jeqk04rs (83,402 Bytes)
Uploading h3jeqk05jr (3,583,778 Bytes)
Uploading h3jeqk06f4 (38,077 Bytes)
Uploading h3jeqk074h (1,654,192 Bytes)
Uploading h3jeqk07rq (86,970 Bytes)
Uploading h3jeqk08da (3,667,704 Bytes)
Uploading h3jeqk08zx (70,563 Bytes)
Uploading h3jeqk09lh (2,875,379 Bytes)
Uploading h3jeqk0a4u (45,362 Bytes)
Uploading h3jeqk0aqj (1,898,771 Bytes)
Uploading h3jeqk0ba9 (119,605 Bytes)
Uploading h3jeqk0bu0 (4,698,516 Bytes)
Uploading h3jeqk0cg9 (492,830,720 Bytes)
Uploading h3jeqk0d2j (38,141 Bytes)
Uploading h3jeqk0dlv (28,674 Bytes)
Uploading h3jeqk0e57 (4,622,328 Bytes)
Upload of h3jeqjy513 completed
Upload of h3jeqjy2yg completed
Upload of h3jeqjybx8 completed
Upload of h3jeqjy7xj completed
Upload of h3jeqjy402 completed
Upload of h3jeqjyqzx completed
Upload of h3jeqjyifh completed
Upload of h3jeqjye56 completed
Upload of h3jeqjyg6u completed
Upload of h3jeqjyh02 completed
Upload of h3jeqjybe6 completed
Upload of h3jeqjy64j completed
Upload of h3jeqjyn35 completed
Upload of h3jeqjyudi completed
Upload of h3jeqjydl2 completed
Upload of h3jeqjyjo7 completed
Upload of h3jeqjyauf completed
Upload of h3jeqjylua completed
Upload of h3jeqjzivf completed
Upload of h3jeqjya9n completed
Upload of h3jeqjy932 completed
Cancelling reservation 9fca79tymud8ld3l5hpvyww78wxfbxe1n4nbgrx8
/usr/lib/node_modules/teambeamjs/node_modules/q/q.js:155
                throw e;
                ^

Error
    at _exceptionToError (/usr/lib/node_modules/teambeamjs/lib/reqHelper.js:228:14)
    at Request.callback [as _callback] (/usr/lib/node_modules/teambeamjs/lib/reqHelper.js:196:17)
    at Request.self.callback (/usr/lib/node_modules/teambeamjs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/lib/node_modules/teambeamjs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/teambeamjs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12) {
  httpStatusCode: 429,
  code: 0
}
[username@servername:/home/username/data]#</pre>

**Comment by technolion** [comment]
Seems to be a `RateLimitException`, because all the uploads start at the same time.
